name: Terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.0  # Specify your desired Terraform version

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform  # Update this path to your Terraform directory

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./terraform  # Update this path to your Terraform directory
